<?php if ($smsg != ""): ?>
<p class="smsg"><?php echo $smsg; ?></p>
<?php endif; ?>
<?php if ($emsg != ""): ?>
<p class="emsg"><?php echo $emsg; ?></p>
<?php endif; ?>
<form action="<?php echo $_SERVER['REQUEST_URI']; ?>" method="post">
	<p>
		<label for="site_name">Site Name:</label>
		<input type="text" name="site_name" id="site_name" value="<?php echo htmlentities($settings['site_name']); ?>" />
	</p>
	<p>
		<input type="submit" value="Update Site Settings" />
	</p>
	<input type="hidden" name="edit_settings_key" value="1" />
</form>