<?php if ($smsg != ""): ?>
<p class="smsg"><?php echo $smsg; ?></p>
<?php endif; ?>
<p class="imsg"><a href="add.php">Add New User</a></p>
<?php if ($total < 1): ?>
<p class="imsg">There are currently <strong>no</strong> users defined.</p>
<?php else: ?>
<p class="imsg">There are currently <strong><?php echo $total; ?></strong> users defined.</p>
<div class="table">
	<table>
		<thead>
			<tr>
				<th>ID</th>
				<th>Username</th>
				<th>Active</th>
				<th>Option</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach($users as $user): ?>
			<tr>
				<td><?php echo $user['id']; ?></td>
				<td><?php echo $user['username']; ?></td>
				<td><?php echo $user['active'] == "1" ? "Yes" : "No"; ?></td>
				<td>
					<a href="edit.php?id=<?php echo $user['id']; ?>">Edit</a> | 
					<a href="view.php?id=<?php echo $user['id']; ?>">View</a> 
				</td>
			</tr>
			<?php endforeach; ?>
		</tbody>
		<tfoot>
			<tr>
				<th>ID</th>
				<th>Username</th>
				<th>Active</th>
				<th>Option</th>
			</tr>
		</tfoot>
	</table>
</div>
<?php endif; ?>