<!DOCTYPE html>
<html lang="en-us" dir="ltr">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width; initial-scale=1.0" />
	<title><?php echo $page_title; ?> | <?php echo get_site_name(); ?></title>
	<link rel="stylesheet" type="text/css" href="<?php echo ADMIN_ROOT; ?>assets/css/style.css" />
	<script type="text/javascript" src="<?php echo ADMIN_ROOT; ?>assets/js/tinymce/tinymce.min.js"></script>
	<script type="text/javascript">
	tinymce.init({
	    selector: ".editor",
	    plugins: [
	        "advlist autolink lists link image charmap print preview anchor",
	        "searchreplace visualblocks code fullscreen",
	        "insertdatetime media table contextmenu paste"
	    ],
	    toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
	});
	</script>
</head>
<body>
	<div id="wrapper">
		<header id="header">
			<h1><?php echo get_site_name(); ?></h1>
		</header>
		<?php if (Session::Exists('username') && Session::Exists('id')): ?>
		<nav id="main-nav">
			<h2 class="hidden">Main Navigation</h2>
			<ul>
				<li><a href="<?php echo ADMIN_ROOT; ?>index.php">Admin Home</a></li>
				<li><a href="<?php echo ADMIN_ROOT; ?>users/index.php">Users</a></li>
				<li><a href="<?php echo ADMIN_ROOT; ?>pages/index.php">Pages</a></li>
				<li><a href="<?php echo ADMIN_ROOT; ?>settings/index.php">Settings</a></li>
				<li><a href="<?php echo ADMIN_ROOT; ?>login.php?logout=true">Logout</a></li>
			</ul>
		</nav>
		<?php endif; ?>
		<section id="main-content">
			<h1><?php echo $page_title; ?></h1>
			<?php echo $content; ?>
		</section>
		<footer id="footer">
			<p>&copy; 2015 | website</p>
		</footer>
	</div>
</body>
</html>